weight = 2
# language code
languageCode = "ko-KR"
# language name
languageName = "한국어"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = true
# copyright description used only for seo schema
copyright = "Licensed under the MIT License."
