disabled = false
weight = 2
# language code
languageCode = "ko-KR"
# language name
languageName = "한국어"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = true
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
