# site description
# 网站描述
description = "임정섭의 개인 웹사이트"
# date format
# 日期格式
# dateFormat = "2006-01-02"
dateFormat = "2006년 1월 2일"
# Search config
# 搜索配置
[search]
  [search.algolia]
    index = "ko_index"
# Home page config
# 主页信息设置
[home]
  # Home page profile
  # 主页个人信息
  [home.profile]
    # title shown in home page (HTML format is supported)
    # 主页显示的网站标题 (支持 HTML 格式)
    title = "임정섭"
    # subtitle shown in home page
    # 主页显示的网站副标题
    subtitle = ""